"""remove score column

Revision ID: 1ee1c906bb02
Revises: 7f63bfa8a902
Create Date: 2026-03-17 23:26:11.136093

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ee1c906bb02"
down_revision: str | Sequence[str] | None = "7f63bfa8a902"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_sessions", "score")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_sessions", sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
