"""add vocabulary tables

Revision ID: 297ec505f124
Revises: 885eb5deac10
Create Date: 2026-04-05 22:15:38.324061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '297ec505f124'
down_revision: Union[str, Sequence[str], None] = '885eb5deac10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # only create vocabulary tables — avoid other autogenerated destructive changes
    op.create_table(
        "vocabulary_lists",
        sa.Column("list_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("industry", sa.String(length=50), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("list_id"),
    )

    op.create_table(
        "vocabulary_words",
        sa.Column("word_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("part_of_speech", sa.String(length=20), nullable=True),
        sa.Column("industry", sa.String(length=50), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("example_sentence", sa.Text(), nullable=True),
        sa.Column("pronunciation_audio_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("word_id"),
    )

    op.create_table(
        "user_vocabulary",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("word_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("retention_score", sa.Float(), nullable=False, server_default=sa.text("2.5")),
        sa.Column("repetition_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("interval_days", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("next_review_date", sa.DateTime(), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("times_correct", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("times_incorrect", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", sa.String(length=20), nullable=False, server_default=sa.text("'learning'")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["word_id"], ["vocabulary_words.word_id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_user_vocabulary_user_id"), "user_vocabulary", ["user_id"], unique=False)
    op.create_index(op.f("ix_user_vocabulary_word_id"), "user_vocabulary", ["word_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # downgrade will remove only the vocabulary tables created here
    op.drop_index(op.f("ix_user_vocabulary_word_id"), table_name="user_vocabulary")
    op.drop_index(op.f("ix_user_vocabulary_user_id"), table_name="user_vocabulary")
    op.drop_table("user_vocabulary")
    op.drop_table("vocabulary_words")
    op.drop_table("vocabulary_lists")
    # ### end Alembic commands ###
