"""Add session_type to InterviewSession

Revision ID: 365c1c9e34e0
Revises: 33cff6125637
Create Date: 2026-04-03 22:48:56.718954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '365c1c9e34e0'
down_revision: Union[str, Sequence[str], None] = '33cff6125637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('session_type', sa.String(), nullable=True))
    op.execute("UPDATE interview_sessions SET session_type = 'mock'")
    op.alter_column('interview_sessions', 'session_type', nullable=False)
    
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_column('interview_sessions', 'session_type')
    op.create_table('listening_assessments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('audio_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_limit_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='listening_assessments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('listening_attempt_answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_option_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cefr_level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), autoincrement=False, nullable=True),
    sa.Column('difficulty_score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['listening_attempts.id'], name='listening_attempt_answers_attempt_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['listening_questions.id'], name='listening_attempt_answers_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['listening_question_options.id'], name='listening_attempt_answers_selected_option_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='listening_attempt_answers_pkey')
    )
    op.create_index('ix_listening_attempt_answers_question_id', 'listening_attempt_answers', ['question_id'], unique=False)
    op.create_index('ix_listening_attempt_answers_attempt_id', 'listening_attempt_answers', ['attempt_id'], unique=False)
    op.create_table('listening_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('cefr_level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), autoincrement=False, nullable=True),
    sa.Column('difficulty_score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['listening_assessments.id'], name='listening_questions_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='listening_questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_listening_questions_assessment_id', 'listening_questions', ['assessment_id'], unique=False)
    op.create_table('behav_questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('behav_questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('trait_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='behav_questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_behav_questions_id', 'behav_questions', ['id'], unique=False)
    op.create_table('reading_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'SUBMITTED', 'EVALUATED', name='assessment_attempt_status_enum'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ability_score', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True),
    sa.Column('cefr_level', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['reading_assessments.id'], name='reading_attempts_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reading_attempts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_reading_attempts_user_id', 'reading_attempts', ['user_id'], unique=False)
    op.create_index('ix_reading_attempts_user_email', 'reading_attempts', ['user_email'], unique=False)
    op.create_index('ix_reading_attempts_status', 'reading_attempts', ['status'], unique=False)
    op.create_index('ix_reading_attempts_assessment_id', 'reading_attempts', ['assessment_id'], unique=False)
    op.create_table('behav_option_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trait_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['behav_options.id'], name='behav_option_scores_option_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='behav_option_scores_pkey')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_users_pkey')
    )
    op.create_index('ix_admin_users_email', 'admin_users', ['email'], unique=True)
    op.create_table('grammar_attempt_answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_option_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cefr_level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), autoincrement=False, nullable=True),
    sa.Column('difficulty_score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['grammar_attempts.id'], name='grammar_attempt_answers_attempt_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['grammar_questions.id'], name='grammar_attempt_answers_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['grammar_question_options.id'], name='grammar_attempt_answers_selected_option_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='grammar_attempt_answers_pkey')
    )
    op.create_index('ix_grammar_attempt_answers_question_id', 'grammar_attempt_answers', ['question_id'], unique=False)
    op.create_index('ix_grammar_attempt_answers_attempt_id', 'grammar_attempt_answers', ['attempt_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('college', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='user_profiles_user_id_key')
    )
    op.create_table('reading_question_options',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], name='reading_question_options_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reading_question_options_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_reading_question_options_question_id', 'reading_question_options', ['question_id'], unique=False)
    op.create_table('listening_question_options',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['listening_questions.id'], name='listening_question_options_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='listening_question_options_pkey')
    )
    op.create_index('ix_listening_question_options_question_id', 'listening_question_options', ['question_id'], unique=False)
    op.create_table('reading_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('cefr_level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), autoincrement=False, nullable=True),
    sa.Column('difficulty_score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['reading_assessments.id'], name='reading_questions_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reading_questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_reading_questions_assessment_id', 'reading_questions', ['assessment_id'], unique=False)
    op.create_table('behav_options',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('behav_options_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['behav_questions.id'], name='behav_options_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='behav_options_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_behav_options_id', 'behav_options', ['id'], unique=False)
    op.create_table('grammar_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('cefr_level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), autoincrement=False, nullable=True),
    sa.Column('difficulty_score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['grammar_assessments.id'], name='grammar_questions_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='grammar_questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_grammar_questions_assessment_id', 'grammar_questions', ['assessment_id'], unique=False)
    op.create_table('behav_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('overall_report', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='behav_attempts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_behav_attempts_user_id', 'behav_attempts', ['user_id'], unique=False)
    op.create_table('reading_assessments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passage_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_limit_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='reading_assessments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('grammar_question_options',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['grammar_questions.id'], name='grammar_question_options_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='grammar_question_options_pkey')
    )
    op.create_index('ix_grammar_question_options_question_id', 'grammar_question_options', ['question_id'], unique=False)
    op.create_table('behav_user_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['behav_attempts.id'], name='behav_user_answers_attempt_id_fkey'),
    sa.ForeignKeyConstraint(['option_id'], ['behav_options.id'], name='behav_user_answers_option_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['behav_questions.id'], name='behav_user_answers_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='behav_user_answers_pkey')
    )
    op.create_index('ix_behav_user_answers_user_id', 'behav_user_answers', ['user_id'], unique=False)
    op.create_table('grammar_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'SUBMITTED', 'EVALUATED', name='assessment_attempt_status_enum'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ability_score', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True),
    sa.Column('cefr_level', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['grammar_assessments.id'], name='grammar_attempts_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='grammar_attempts_pkey')
    )
    op.create_index('ix_grammar_attempts_user_id', 'grammar_attempts', ['user_id'], unique=False)
    op.create_index('ix_grammar_attempts_user_email', 'grammar_attempts', ['user_email'], unique=False)
    op.create_index('ix_grammar_attempts_status', 'grammar_attempts', ['status'], unique=False)
    op.create_index('ix_grammar_attempts_assessment_id', 'grammar_attempts', ['assessment_id'], unique=False)
    op.create_table('listening_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'SUBMITTED', 'EVALUATED', name='assessment_attempt_status_enum'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ability_score', sa.NUMERIC(precision=6, scale=4), autoincrement=False, nullable=True),
    sa.Column('cefr_level', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['listening_assessments.id'], name='listening_attempts_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='listening_attempts_pkey')
    )
    op.create_index('ix_listening_attempts_user_id', 'listening_attempts', ['user_id'], unique=False)
    op.create_index('ix_listening_attempts_user_email', 'listening_attempts', ['user_email'], unique=False)
    op.create_index('ix_listening_attempts_status', 'listening_attempts', ['status'], unique=False)
    op.create_index('ix_listening_attempts_assessment_id', 'listening_attempts', ['assessment_id'], unique=False)
    op.create_table('reading_attempt_answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_option_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cefr_level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level_enum'), autoincrement=False, nullable=True),
    sa.Column('difficulty_score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['reading_attempts.id'], name='reading_attempt_answers_attempt_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['reading_questions.id'], name='reading_attempt_answers_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['reading_question_options.id'], name='reading_attempt_answers_selected_option_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='reading_attempt_answers_pkey')
    )
    op.create_index('ix_reading_attempt_answers_question_id', 'reading_attempt_answers', ['question_id'], unique=False)
    op.create_index('ix_reading_attempt_answers_attempt_id', 'reading_attempt_answers', ['attempt_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_progress_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_progress_pkey'),
    sa.UniqueConstraint('user_id', 'module_type', 'module_id', name='uq_user_module')
    )
    op.create_table('grammar_assessments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_limit_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='grammar_assessments_pkey')
    )
    # ### end Alembic commands ###
