"""Align user schema with Pod 1

Revision ID: 459f2e3351f5
Revises: 365c1c9e34e0
Create Date: 2026-04-03 23:12:58.895310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '459f2e3351f5'
down_revision: Union[str, Sequence[str], None] = '365c1c9e34e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use rename instead of drop/add to keep data
    op.alter_column('users', 'hashed_password', new_column_name='password_hash')
    op.alter_column('users', 'password_hash', type_=sa.String(length=255), nullable=True)

    op.add_column('users', sa.Column('oauth_sub', sa.String(length=255), nullable=True))
    
    # Handle NOT NULL for is_active
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_active = true")
    op.alter_column('users', 'is_active', nullable=False)

    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'oauth_sub')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
