"""standardize_user_id_to_uuid

Revision ID: 4ffd209d425d
Revises: 3ba7caef91b2
Create Date: 2026-04-03 23:56:33.483911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffd209d425d'
down_revision: Union[str, Sequence[str], None] = '3ba7caef91b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'session_type')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.add_column('interview_sessions', sa.Column('session_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
