"""remove_description_and_instructions_columns

Revision ID: 620aa2067f08
Revises: eb8a0f843e26
Create Date: 2026-03-24 10:42:31.468138

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '620aa2067f08'
down_revision: str | Sequence[str] | None = 'eb8a0f843e26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grammar_assessments", "description")
    op.drop_column("grammar_assessments", "instructions")
    op.drop_column("listening_assessments", "description")
    op.drop_column("listening_assessments", "instructions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listening_assessments",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "listening_assessments",
        sa.Column("instructions", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "grammar_assessments",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "grammar_assessments",
        sa.Column("instructions", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
