"""add is_correct column to user_responses

Revision ID: 7f63bfa8a902
Revises: 8eb47ef58780
Create Date: 2026-03-17 22:28:25.479012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f63bfa8a902'
down_revision: Union[str, Sequence[str], None] = '8eb47ef58780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_responses', 'is_correct')
    # ### end Alembic commands ###
