"""create grammar tables

Revision ID: 80ce8d6daf0a
Revises: 39ec670c6d48
Create Date: 2026-03-17 22:52:18.207911

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80ce8d6daf0a"
down_revision: str | Sequence[str] | None = "39ec670c6d48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grammar_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("topic", sa.String(length=255), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grammar_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("user_email", sa.String(length=320), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "IN_PROGRESS",
                "SUBMITTED",
                "EVALUATED",
                name="assessment_attempt_status_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("answered_questions", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assessment_id"], ["grammar_assessments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grammar_attempts_assessment_id"),
        "grammar_attempts",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_grammar_attempts_status"), "grammar_attempts", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_grammar_attempts_user_email"), "grammar_attempts", ["user_email"], unique=False
    )
    op.create_index(
        op.f("ix_grammar_attempts_user_id"), "grammar_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "grammar_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("points", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assessment_id"], ["grammar_assessments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grammar_questions_assessment_id"),
        "grammar_questions",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "grammar_question_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("option_text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["question_id"], ["grammar_questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grammar_question_options_question_id"),
        "grammar_question_options",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "grammar_attempt_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("selected_option_id", sa.UUID(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["attempt_id"], ["grammar_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["grammar_questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["selected_option_id"], ["grammar_question_options.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grammar_attempt_answers_attempt_id"),
        "grammar_attempt_answers",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_grammar_attempt_answers_question_id"),
        "grammar_attempt_answers",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_grammar_attempt_answers_question_id"), table_name="grammar_attempt_answers"
    )
    op.drop_index(
        op.f("ix_grammar_attempt_answers_attempt_id"), table_name="grammar_attempt_answers"
    )
    op.drop_table("grammar_attempt_answers")
    op.drop_index(
        op.f("ix_grammar_question_options_question_id"), table_name="grammar_question_options"
    )
    op.drop_table("grammar_question_options")
    op.drop_index(op.f("ix_grammar_questions_assessment_id"), table_name="grammar_questions")
    op.drop_table("grammar_questions")
    op.drop_index(op.f("ix_grammar_attempts_user_id"), table_name="grammar_attempts")
    op.drop_index(op.f("ix_grammar_attempts_user_email"), table_name="grammar_attempts")
    op.drop_index(op.f("ix_grammar_attempts_status"), table_name="grammar_attempts")
    op.drop_index(op.f("ix_grammar_attempts_assessment_id"), table_name="grammar_attempts")
    op.drop_table("grammar_attempts")
    op.drop_table("grammar_assessments")
    # ### end Alembic commands ###
