"""autogen: vocab models

Revision ID: 83b909912715
Revises: db943f6fb8e8
Create Date: 2026-04-08 22:08:18.477690

"""

import contextlib
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83b909912715"
down_revision: str | Sequence[str] | None = "db943f6fb8e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands adjusted — keep only safe vocabulary changes ###
    op.add_column(
        "user_vocabulary", sa.Column("last_response_time_ms", sa.Integer(), nullable=True)
    )
    # add unique constraint to prevent duplicate (user_id, word_id)
    op.create_unique_constraint("uq_user_word", "user_vocabulary", ["user_id", "word_id"])

    op.add_column("vocabulary_lists", sa.Column("cefr_level", sa.String(length=5), nullable=True))
    op.execute(
        sa.text(
            "UPDATE vocabulary_lists SET cefr_level = difficulty WHERE cefr_level IS NULL AND difficulty IS NOT NULL"
        )
    )
    # remove the old difficulty column if present
    with contextlib.suppress(Exception):
        op.drop_column("vocabulary_lists", "difficulty")

    op.add_column("vocabulary_words", sa.Column("cefr_level", sa.String(length=5), nullable=True))
    op.execute(
        sa.text(
            "UPDATE vocabulary_words SET cefr_level = difficulty WHERE cefr_level IS NULL AND difficulty IS NOT NULL"
        )
    )
    bind = op.get_bind()
    null_count = bind.scalar(
        sa.text("SELECT COUNT(*) FROM vocabulary_words WHERE cefr_level IS NULL")
    )
    if null_count == 0:
        op.alter_column(
            "vocabulary_words", "cefr_level", existing_type=sa.String(length=5), nullable=False
        )
    with contextlib.suppress(Exception):
        op.drop_index(op.f("ix_vocabulary_words_list_id"), table_name="vocabulary_words")
    with contextlib.suppress(Exception):
        op.drop_column("vocabulary_words", "difficulty")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vocabulary_words",
        sa.Column("difficulty", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_vocabulary_words_list_id"), "vocabulary_words", ["list_id"], unique=False
    )
    op.drop_column("vocabulary_words", "cefr_level")
    op.add_column(
        "vocabulary_lists",
        sa.Column("difficulty", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.drop_column("vocabulary_lists", "cefr_level")
    op.create_foreign_key(
        op.f("user_vocabulary_user_id_fkey"), "user_vocabulary", "users", ["user_id"], ["id"]
    )
    op.drop_constraint("uq_user_word", "user_vocabulary", type_="unique")
    op.drop_column("user_vocabulary", "last_response_time_ms")
    op.create_foreign_key(
        op.f("user_profiles_user_id_fkey"),
        "user_profiles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_user_profiles_user_id"), table_name="user_profiles")
    op.create_unique_constraint(
        op.f("user_profiles_user_id_key"),
        "user_profiles",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "user_profiles",
        "dob",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "user_profiles",
        "user_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "reading_attempts",
        "user_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "listening_attempts",
        "user_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "grammar_attempts",
        "user_id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.create_table(
        "test_sessions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("current_topic", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("current_subtopic", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("question_index", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("correct_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("total_correct", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("total_questions", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("passed_subtopics", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("failed_subtopics", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("completed_subtopics", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("test_sessions_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("test_sessions_pkey")),
    )
    op.create_index(op.f("ix_test_sessions_id"), "test_sessions", ["id"], unique=False)
    op.create_table(
        "user_answers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("selected_answer", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("user_answers_question_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["test_sessions.id"], name=op.f("user_answers_session_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_answers_pkey")),
    )
    op.create_index(op.f("ix_user_answers_id"), "user_answers", ["id"], unique=False)
    op.create_table(
        "passage_answers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("selected_answer", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["comprehension_questions.id"],
            name=op.f("passage_answers_question_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["passage_sessions.id"], name=op.f("passage_answers_session_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("passage_answers_pkey")),
    )
    op.create_index(
        op.f("ix_passage_answers_session_id"), "passage_answers", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_passage_answers_question_id"), "passage_answers", ["question_id"], unique=False
    )
    op.create_table(
        "behav_user_answers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("attempt_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("option_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["behav_attempts.id"], name=op.f("behav_user_answers_attempt_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["option_id"], ["behav_options.id"], name=op.f("behav_user_answers_option_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["behav_questions.id"],
            name=op.f("behav_user_answers_question_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("behav_user_answers_pkey")),
    )
    op.create_index(
        op.f("ix_behav_user_answers_user_id"), "behav_user_answers", ["user_id"], unique=False
    )
    op.create_table(
        "comprehension_questions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("passage_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("question", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "options", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.Column("correct_answer", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("difficulty", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("explanation", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
            name=op.f("comprehension_questions_passage_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comprehension_questions_pkey")),
    )
    op.create_index(
        op.f("ix_comprehension_questions_passage_id"),
        "comprehension_questions",
        ["passage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_comprehension_questions_difficulty"),
        "comprehension_questions",
        ["difficulty"],
        unique=False,
    )
    op.create_table(
        "key_skills",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("keyword", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("key_skills_pkey")),
    )
    op.create_index(op.f("ix_key_skills_user_id"), "key_skills", ["user_id"], unique=False)
    op.create_index(op.f("ix_key_skills_keyword"), "key_skills", ["keyword"], unique=False)
    op.create_table(
        "passage_sessions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("passage_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["passage_id"], ["passages.id"], name=op.f("passage_sessions_passage_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("passage_sessions_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("passage_sessions_pkey")),
    )
    op.create_index(
        op.f("ix_passage_sessions_user_id"), "passage_sessions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_passage_sessions_passage_id"), "passage_sessions", ["passage_id"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("skill_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("answer_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "difficulty",
            postgresql.ENUM("EASY", "MEDIUM", "HARD", name="difficultylevel"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "options",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["key_skills.id"], name=op.f("questions_skill_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("questions_pkey")),
    )
    op.create_table(
        "interview_questions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("skill_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "options",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("answer_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "difficulty",
            postgresql.ENUM("EASY", "MEDIUM", "HARD", name="difficultylevel"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["key_skills.id"], name=op.f("interview_questions_skill_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("interview_questions_pkey")),
    )
    op.create_table(
        "interview_sessions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("feedback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("interview_sessions_pkey")),
    )
    op.create_index(
        op.f("ix_interview_sessions_user_id"), "interview_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "behav_attempts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "overall_report",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "scores", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("submitted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("behav_attempts_pkey")),
    )
    op.create_index(op.f("ix_behav_attempts_user_id"), "behav_attempts", ["user_id"], unique=False)
    op.create_table(
        "behav_options",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("option_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("option_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["behav_questions.id"], name=op.f("behav_options_question_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("behav_options_pkey")),
    )
    op.create_index(op.f("ix_behav_options_id"), "behav_options", ["id"], unique=False)
    op.create_table(
        "user_responses",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_answer", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("feedback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("user_responses_question_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["interview_sessions.id"], name=op.f("user_responses_session_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_responses_pkey")),
    )
    op.create_table(
        "behav_questions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("trait_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("behav_questions_pkey")),
    )
    op.create_index(op.f("ix_behav_questions_id"), "behav_questions", ["id"], unique=False)
    op.create_table(
        "behav_option_scores",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("option_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("trait_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("score_value", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["option_id"], ["behav_options.id"], name=op.f("behav_option_scores_option_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("behav_option_scores_pkey")),
    )
    op.create_table(
        "passages",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("passages_pkey")),
    )
    # ### end Alembic commands ###
