"""make session_id nullable in user_responses

Revision ID: 8eb47ef58780
Revises: dd383972b9d9
Create Date: 2026-03-17 22:23:18.324560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb47ef58780'
down_revision: Union[str, Sequence[str], None] = 'dd383972b9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_responses', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_responses', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
