"""add_cefr_to_sentence_framing

Revision ID: b0fd3c343aa2
Revises: 6cf5cdad4292
Create Date: 2026-04-06 15:20:29.652818

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0fd3c343aa2"
down_revision: str | Sequence[str] | None = "6cf5cdad4292"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grammar_attempt_answers",
        sa.Column(
            "cefr_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefr_level_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "grammar_attempt_answers",
        sa.Column("difficulty_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "grammar_attempts",
        sa.Column("ability_score", sa.Numeric(precision=6, scale=4), nullable=True),
    )
    op.add_column("grammar_attempts", sa.Column("cefr_level", sa.String(length=3), nullable=True))
    op.drop_column("grammar_attempts", "score")
    op.add_column(
        "grammar_questions",
        sa.Column(
            "cefr_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefr_level_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "grammar_questions",
        sa.Column("difficulty_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "listening_attempt_answers",
        sa.Column(
            "cefr_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefr_level_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "listening_attempt_answers",
        sa.Column("difficulty_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "listening_attempts",
        sa.Column("ability_score", sa.Numeric(precision=6, scale=4), nullable=True),
    )
    op.add_column("listening_attempts", sa.Column("cefr_level", sa.String(length=3), nullable=True))
    op.drop_column("listening_attempts", "score")
    op.add_column(
        "listening_questions",
        sa.Column(
            "cefr_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefr_level_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "listening_questions",
        sa.Column("difficulty_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "reading_attempt_answers",
        sa.Column(
            "cefr_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefr_level_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "reading_attempt_answers",
        sa.Column("difficulty_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "reading_attempts",
        sa.Column("ability_score", sa.Numeric(precision=6, scale=4), nullable=True),
    )
    op.add_column("reading_attempts", sa.Column("cefr_level", sa.String(length=3), nullable=True))
    op.drop_column("reading_attempts", "score")
    op.add_column(
        "reading_questions",
        sa.Column(
            "cefr_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefr_level_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "reading_questions",
        sa.Column("difficulty_score", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "sentence_exercises",
        sa.Column(
            "cefr_level",
            sa.Enum("A1", "A2", "B1", "B2", "C1", "C2", name="cefr_level_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "sentence_exercises",
        sa.Column("difficulty_score", sa.NUMERIC(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "user_progress",
        sa.Column("honesty_humility", sa.DECIMAL(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "user_progress", sa.Column("emotionality", sa.DECIMAL(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "user_progress", sa.Column("extraversion", sa.DECIMAL(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "user_progress", sa.Column("agreeableness", sa.DECIMAL(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "user_progress",
        sa.Column("conscientiousness", sa.DECIMAL(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "user_progress", sa.Column("openness", sa.DECIMAL(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "user_sentence_submissions", sa.Column("cefr_level", sa.String(length=3), nullable=True)
    )
    op.add_column(
        "user_sentence_submissions",
        sa.Column("ability_score", sa.NUMERIC(precision=6, scale=4), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_sentence_submissions", "ability_score")
    op.drop_column("user_sentence_submissions", "cefr_level")
    op.drop_column("user_progress", "openness")
    op.drop_column("user_progress", "conscientiousness")
    op.drop_column("user_progress", "agreeableness")
    op.drop_column("user_progress", "extraversion")
    op.drop_column("user_progress", "emotionality")
    op.drop_column("user_progress", "honesty_humility")
    op.drop_column("sentence_exercises", "difficulty_score")
    op.drop_column("sentence_exercises", "cefr_level")
    op.drop_column("reading_questions", "difficulty_score")
    op.drop_column("reading_questions", "cefr_level")
    op.add_column(
        "reading_attempts",
        sa.Column("score", sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    )
    op.drop_column("reading_attempts", "cefr_level")
    op.drop_column("reading_attempts", "ability_score")
    op.drop_column("reading_attempt_answers", "difficulty_score")
    op.drop_column("reading_attempt_answers", "cefr_level")
    op.drop_column("listening_questions", "difficulty_score")
    op.drop_column("listening_questions", "cefr_level")
    op.add_column(
        "listening_attempts",
        sa.Column("score", sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    )
    op.drop_column("listening_attempts", "cefr_level")
    op.drop_column("listening_attempts", "ability_score")
    op.drop_column("listening_attempt_answers", "difficulty_score")
    op.drop_column("listening_attempt_answers", "cefr_level")
    op.drop_column("grammar_questions", "difficulty_score")
    op.drop_column("grammar_questions", "cefr_level")
    op.add_column(
        "grammar_attempts",
        sa.Column("score", sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    )
    op.drop_column("grammar_attempts", "cefr_level")
    op.drop_column("grammar_attempts", "ability_score")
    op.drop_column("grammar_attempt_answers", "difficulty_score")
    op.drop_column("grammar_attempt_answers", "cefr_level")
    # ### end Alembic commands ###
