"""add options column to questions

Revision ID: dd383972b9d9
Revises: fba08d3a18bc
Create Date: 2026-03-17 21:55:56.307224

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd383972b9d9"
down_revision: str | Sequence[str] | None = "fba08d3a18bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("options", sa.JSON(), server_default="[]", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "options")
    # ### end Alembic commands ###
