"""added users onboarding column

Revision ID: eb8a0f843e26
Revises: ce4b0ae28bd6
Create Date: 2026-03-18 20:28:31.348456

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb8a0f843e26"
down_revision: str | Sequence[str] | None = "ce4b0ae28bd6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("mobile", sa.String(length=20), nullable=False),
        sa.Column("dob", sa.String(length=10), nullable=False),
        sa.Column("college", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column(
        "users",
        sa.Column("profile_completed", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.drop_constraint(op.f("users_oauth_sub_key"), "users", type_="unique")
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint(
        op.f("users_oauth_sub_key"), "users", ["oauth_sub"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "profile_completed")
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
