"""create reading tables

Revision ID: 5b9db33a16fc
Revises:
Create Date: 2026-03-17 22:49:37.212902

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b9db33a16fc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_assessments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("passage_text", sa.Text(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reading_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("user_email", sa.String(length=320), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "SUBMITTED", "EVALUATED", name="assessment_attempt_status_enum"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("answered_questions", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assessment_id"], ["reading_assessments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_attempts_assessment_id"),
        "reading_attempts",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_attempts_status"), "reading_attempts", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_reading_attempts_user_email"), "reading_attempts", ["user_email"], unique=False
    )
    op.create_index(
        op.f("ix_reading_attempts_user_id"), "reading_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "reading_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("points", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assessment_id"], ["reading_assessments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_questions_assessment_id"),
        "reading_questions",
        ["assessment_id"],
        unique=False,
    )
    op.create_table(
        "reading_question_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("option_text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["question_id"], ["reading_questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_question_options_question_id"),
        "reading_question_options",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "reading_attempt_answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("selected_option_id", sa.UUID(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["attempt_id"], ["reading_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["reading_questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["selected_option_id"], ["reading_question_options.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_attempt_answers_attempt_id"),
        "reading_attempt_answers",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_attempt_answers_question_id"),
        "reading_attempt_answers",
        ["question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reading_attempt_answers_question_id"), table_name="reading_attempt_answers"
    )
    op.drop_index(
        op.f("ix_reading_attempt_answers_attempt_id"), table_name="reading_attempt_answers"
    )
    op.drop_table("reading_attempt_answers")
    op.drop_index(
        op.f("ix_reading_question_options_question_id"), table_name="reading_question_options"
    )
    op.drop_table("reading_question_options")
    op.drop_index(op.f("ix_reading_questions_assessment_id"), table_name="reading_questions")
    op.drop_table("reading_questions")
    op.drop_index(op.f("ix_reading_attempts_user_id"), table_name="reading_attempts")
    op.drop_index(op.f("ix_reading_attempts_user_email"), table_name="reading_attempts")
    op.drop_index(op.f("ix_reading_attempts_status"), table_name="reading_attempts")
    op.drop_index(op.f("ix_reading_attempts_assessment_id"), table_name="reading_attempts")
    op.drop_table("reading_attempts")
    op.drop_table("reading_assessments")
    # ### end Alembic commands ###
